# Temporal conformance harness.
#
# The fixtures in fixtures/temporal/ are generated by tools/temporal-oracle/
# from the reference Temporal polyfill. Each case is an operation (`op`) on a
# receiver string with arguments and options, and Temporal's result as a
# string (or the JavaScript error class). This file maps each `op` to zeitig
# and runs all cases of one op and one set of options in a single vectorised
# call, falling back to one call per case only to locate errors.

conformance_types <- c(
  "plain-date", "plain-time", "plain-date-time", "duration", "instant", "zoned-date-time"
)

conformance_load <- function(type) {
  path <- test_path("fixtures", "temporal", paste0(type, ".json"))
  zujson::json_parse_file(path, simplify = FALSE)$cases
}

conformance_parsers <- list(
  "plain-date" = function(x) plain_date(x),
  "plain-time" = function(x) plain_time(x),
  "plain-date-time" = function(x) plain_date_time(x),
  "instant" = function(x) instant(x),
  "zoned-date-time" = function(x) zoned_date_time(x),
  "duration" = function(x) duration(x)
)

conformance_constructors <- list(
  "plain-date" = plain_date,
  "plain-time" = plain_time,
  "plain-date-time" = plain_date_time,
  "zoned-date-time" = zoned_date_time,
  "duration" = duration
)

conformance_getters <- list(
  year = year, month = month, day = day, hour = hour, minute = minute, second = second,
  millisecond = millisecond, microsecond = microsecond, nanosecond = nanosecond,
  dayOfWeek = day_of_week, dayOfYear = day_of_year, weekOfYear = week_of_year,
  yearOfWeek = year_of_week, daysInWeek = days_in_week, daysInMonth = days_in_month,
  daysInYear = days_in_year, monthsInYear = months_in_year, inLeapYear = in_leap_year,
  hoursInDay = hours_in_day, offset = offset, offsetNanoseconds = offset_nanoseconds,
  timeZoneId = time_zone, epochMilliseconds = epoch_milliseconds,
  epochNanoseconds = epoch_nanoseconds, blank = duration_blank,
  sign = function(x) as.integer(sign(x))
)
for (unit in c(
  "years", "months", "weeks", "days", "hours", "minutes", "seconds", "milliseconds",
  "microseconds", "nanoseconds"
)) {
  local({
    u <- unit
    conformance_getters[[u]] <<- function(x) vctrs::field(x, u)
  })
}

# camelCase -> snake_case for option and field names.
conformance_snake <- function(x) {
  gsub("([A-Z])", "_\\L\\1", x, perl = TRUE)
}

conformance_options <- function(o) {
  if (is.null(o)) {
    return(list())
  }
  names(o) <- conformance_snake(names(o))
  o
}

# A list of property bags (one per case) as a list of columns.
conformance_columns <- function(bags) {
  keys <- names(bags[[1]])
  cols <- lapply(keys, function(k) unlist(lapply(bags, `[[`, k)))
  names(cols) <- conformance_snake(keys)
  cols
}

# Each op: function(type, receiver, arg, options) where `receiver` is a
# character vector, `arg` is the vector (or list of property bags) of first
# arguments and `options` a named list shared by all cases.
conformance_ops <- list(
  from = function(type, rec, arg, o) {
    if (type == "zoned-date-time") {
      return(rlang::exec(zoned_date_time, rec, !!!o))
    }
    conformance_parsers[[type]](rec)
  },
  from_fields = function(type, rec, arg, o) {
    rlang::exec(conformance_constructors[[type]], !!!conformance_columns(arg), !!!o)
  },
  add = function(type, rec, arg, o) {
    rlang::exec(temporal_add, conformance_parsers[[type]](rec), arg, !!!o)
  },
  subtract = function(type, rec, arg, o) {
    rlang::exec(temporal_subtract, conformance_parsers[[type]](rec), arg, !!!o)
  },
  until = function(type, rec, arg, o) {
    p <- conformance_parsers[[type]]
    rlang::exec(temporal_until, p(rec), p(arg), !!!o)
  },
  since = function(type, rec, arg, o) {
    p <- conformance_parsers[[type]]
    rlang::exec(temporal_since, p(rec), p(arg), !!!o)
  },
  round = function(type, rec, arg, o) {
    rlang::exec(temporal_round, conformance_parsers[[type]](rec), !!!o)
  },
  with = function(type, rec, arg, o) {
    rlang::exec(
      temporal_with, conformance_parsers[[type]](rec), !!!conformance_columns(arg), !!!o
    )
  },
  toString = function(type, rec, arg, o) {
    rlang::exec(format, conformance_parsers[[type]](rec), !!!o)
  },
  compare = function(type, rec, arg, o) {
    p <- conformance_parsers[[type]]
    if (type == "duration") {
      return(duration_compare(p(rec), p(arg), relative_to = o$relative_to))
    }
    temporal_compare(p(rec), p(arg))
  },
  equals = function(type, rec, arg, o) {
    p <- conformance_parsers[[type]]
    temporal_equals(p(rec), p(arg))
  },
  get = function(type, rec, arg, o) {
    conformance_getters[[arg[[1]]]](conformance_parsers[[type]](rec))
  },
  negated = function(type, rec, arg, o) -conformance_parsers[[type]](rec),
  abs = function(type, rec, arg, o) abs(conformance_parsers[[type]](rec)),
  total = function(type, rec, arg, o) {
    duration_total(conformance_parsers[[type]](rec), o$unit, relative_to = o$relative_to)
  },
  withTimeZone = function(type, rec, arg, o) {
    with_time_zone(conformance_parsers[[type]](rec), arg)
  },
  startOfDay = function(type, rec, arg, o) start_of_day(conformance_parsers[[type]](rec)),
  getTimeZoneTransition = function(type, rec, arg, o) {
    time_zone_transition(conformance_parsers[[type]](rec), arg[[1]])
  },
  toZonedDateTime = function(type, rec, arg, o) {
    rlang::exec(to_zoned_date_time, conformance_parsers[[type]](rec), arg, !!!o)
  },
  toZonedDateTimeISO = function(type, rec, arg, o) {
    to_zoned_date_time(conformance_parsers[[type]](rec), arg)
  },
  toInstant = function(type, rec, arg, o) to_instant(conformance_parsers[[type]](rec)),
  toPlainDateTime = function(type, rec, arg, o) {
    to_plain_date_time(conformance_parsers[[type]](rec))
  },
  fromEpochNanoseconds = function(type, rec, arg, o) instant_from_epoch(nanoseconds = arg),
  fromEpochMilliseconds = function(type, rec, arg, o) {
    instant_from_epoch(milliseconds = as.numeric(arg))
  }
)

# Ops whose first argument is the same for the whole group.
conformance_scalar_arg_ops <- c("get", "getTimeZoneTransition")

# zeitig values as Temporal-style strings.
conformance_as_string <- function(x) {
  if (is.character(x)) {
    out <- x
  } else if (is.logical(x)) {
    out <- ifelse(x, "true", "false")
  } else if (is.numeric(x)) {
    out <- format(x, digits = 17, scientific = FALSE, trim = TRUE)
    out <- sub("\\.?0+$", "", ifelse(grepl("\\.", out), out, paste0(out, ".")))
  } else {
    out <- format(x)
  }
  out[is.na(x)] <- "null"
  unname(out)
}

conformance_error_classes <- c(
  RangeError = "zeitig_range_error",
  TypeError = "zeitig_type_error"
)

# Runs one op on a group of cases. Returns a character vector: the result as a
# string, or "error:<class>" naming the zeitig condition class (or the first
# class of a non-zeitig error).
conformance_eval <- function(type, op, cases) {
  fn <- conformance_ops[[op]]
  rec <- vapply(cases, function(c) c$receiver %||% NA_character_, character(1))
  first <- lapply(cases, function(c) c$args[[1]])
  arg <- if (length(first) && (is.list(first[[1]]) || is.null(first[[1]]))) {
    first
  } else {
    unlist(first)
  }
  o <- conformance_options(cases[[1]]$options)
  call <- function(rec, arg) {
    tryCatch(
      conformance_as_string(fn(type, rec, arg, o)),
      error = function(e) {
        cls <- intersect(class(e), conformance_error_classes)
        paste0("error:", if (length(cls)) cls[[1]] else class(e)[[1]])
      }
    )
  }
  out <- if (length(cases) > 1) call(rec, arg) else character()
  if (length(out) != length(cases)) {
    out <- vapply(seq_along(cases), function(i) call(rec[i], arg[i]), character(1))
  }
  out
}

conformance_expected <- function(case) {
  if (!is.null(case$zeitig_result) || !is.null(case$zeitig_error)) {
    error <- case$zeitig_error
    result <- case$zeitig_result
  } else {
    error <- case$error
    result <- case$result
  }
  if (!is.null(error)) {
    paste0("error:", conformance_error_classes[[error]])
  } else {
    result
  }
}

conformance_same <- function(expected, actual) {
  if (identical(expected, actual)) {
    return(TRUE)
  }
  e <- suppressWarnings(as.numeric(expected))
  a <- suppressWarnings(as.numeric(actual))
  !is.na(e) && !is.na(a) && abs(e - a) <= 1e-12 * max(1, abs(e))
}

# Runs all cases of a fixture and classifies each one:
# * "match": zeitig gives Temporal's result (or raises the mapped error);
# * "documented": a documented divergence where zeitig gives its documented
#   result;
# * "skipped": a documented divergence without a recorded zeitig result;
# * "mismatch": anything else.
conformance_run <- function(type, cases = conformance_load(type)) {
  key <- vapply(cases, function(c) {
    a <- c$args[[1]]
    paste(
      c$op,
      paste(names(c$options), unlist(c$options), sep = "=", collapse = ";"),
      if (c$op %in% conformance_scalar_arg_ops) a,
      if (is.list(a)) paste(names(a), collapse = ","),
      # Cases expected to fail run on their own so they cannot mask others.
      if (!is.null(c$zeitig_error) || (is.null(c$zeitig_result) && !is.null(c$error))) c$id
    )
  }, character(1))
  actual <- character(length(cases))
  for (k in unique(key)) {
    idx <- which(key == k)
    actual[idx] <- conformance_eval(type, cases[[idx[1]]]$op, cases[idx])
  }
  expected <- vapply(cases, function(c) conformance_expected(c) %||% "null", character(1))
  same <- mapply(conformance_same, expected, actual)
  divergent <- vapply(cases, function(c) !is.null(c$divergence), logical(1))
  checked <- vapply(cases, function(c) {
    is.null(c$divergence) || !is.null(c$zeitig_result) || !is.null(c$zeitig_error)
  }, logical(1))
  status <- ifelse(!checked, "skipped", ifelse(!same, "mismatch",
    ifelse(divergent, "documented", "match")
  ))
  data.frame(
    id = vapply(cases, `[[`, character(1), "id"),
    op = vapply(cases, `[[`, character(1), "op"),
    divergence = vapply(cases, function(c) c$divergence %||% NA_character_, character(1)),
    expected = expected,
    actual = actual,
    status = status,
    stringsAsFactors = FALSE
  )
}

conformance_describe <- function(res, n = 30) {
  bad <- res[res$status == "mismatch", , drop = FALSE]
  lines <- sprintf("%s: expected %s, got %s", bad$id, bad$expected, bad$actual)
  if (length(lines) > n) {
    lines <- c(lines[seq_len(n)], sprintf("... and %d more", length(lines) - n))
  }
  paste(lines, collapse = "\n")
}
