test_that("now_*() return current values", {
  a <- now_instant()
  expect_s3_class(a, "zietig_instant")
  expect_length(a, 1)
  ct <- Sys.time()
  expect_lt(abs(as.double(as.POSIXct(a)) - as.double(ct)), 60)
  z <- now_zoned_date_time("Asia/Tokyo")
  expect_equal(time_zone(z), "Asia/Tokyo")
  expect_s3_class(now_plain_date("UTC"), "zietig_plain_date")
  expect_s3_class(now_plain_time("UTC"), "zietig_plain_time")
  expect_s3_class(now_plain_date_time("UTC"), "zietig_plain_date_time")
  expect_type(now_time_zone(), "character")
  expect_error(now_zoned_date_time("Not/AZone"), class = "zietig_range_error")
})

test_that("the default time zone follows TZ", {
  old <- Sys.getenv("TZ", unset = NA)
  on.exit(if (is.na(old)) Sys.unsetenv("TZ") else Sys.setenv(TZ = old))
  Sys.setenv(TZ = "Asia/Kolkata")
  expect_equal(now_time_zone(), "Asia/Kolkata")
  expect_equal(time_zone(now_zoned_date_time()), "Asia/Kolkata")
  expect_equal(offset(now_zoned_date_time()), "+05:30")
  ct <- as.POSIXct("2020-01-01 12:00:00")
  expect_equal(time_zone(as_zoned_date_time(ct)), "Asia/Kolkata")
  Sys.setenv(TZ = "Invalid/Zone_Name")
  expect_true(now_time_zone() %in% c("UTC", available_time_zones()))
})
