# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib zudate, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_zudate__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_zudate__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`rs_available_time_zones` <- function() {
  .Call(savvy_rs_available_time_zones__impl)
}


`rs_plain_date_field` <- function(`year`, `month`, `day`, `field`) {
  .Call(savvy_rs_plain_date_field__impl, `year`, `month`, `day`, `field`)
}


`rs_plain_date_format` <- function(`year`, `month`, `day`) {
  .Call(savvy_rs_plain_date_format__impl, `year`, `month`, `day`)
}


`rs_plain_date_from_epoch_days` <- function(`days`) {
  .Call(savvy_rs_plain_date_from_epoch_days__impl, `days`)
}


`rs_plain_date_from_parts` <- function(`year`, `month`, `day`, `reject`) {
  .Call(savvy_rs_plain_date_from_parts__impl, `year`, `month`, `day`, `reject`)
}


`rs_plain_date_parse` <- function(`x`) {
  .Call(savvy_rs_plain_date_parse__impl, `x`)
}


`rs_plain_date_time_format` <- function(`year`, `month`, `day`, `second_of_day`, `nanos`) {
  .Call(savvy_rs_plain_date_time_format__impl, `year`, `month`, `day`, `second_of_day`, `nanos`)
}


`rs_plain_date_time_parse` <- function(`x`) {
  .Call(savvy_rs_plain_date_time_parse__impl, `x`)
}


`rs_plain_date_to_epoch_days` <- function(`year`, `month`, `day`) {
  .Call(savvy_rs_plain_date_to_epoch_days__impl, `year`, `month`, `day`)
}


`rs_plain_time_format` <- function(`second_of_day`, `nanos`) {
  .Call(savvy_rs_plain_time_format__impl, `second_of_day`, `nanos`)
}


`rs_plain_time_from_parts` <- function(`hour`, `minute`, `second`, `millisecond`, `microsecond`, `nanosecond`, `reject`) {
  .Call(savvy_rs_plain_time_from_parts__impl, `hour`, `minute`, `second`, `millisecond`, `microsecond`, `nanosecond`, `reject`)
}


`rs_plain_time_parse` <- function(`x`) {
  .Call(savvy_rs_plain_time_parse__impl, `x`)
}


