# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib zudate, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_zudate__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_zudate__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`rs_available_time_zones` <- function() {
  .Call(savvy_rs_available_time_zones__impl)
}


`rs_duration_add` <- function(`x`, `y`) {
  .Call(savvy_rs_duration_add__impl, `x`, `y`)
}


`rs_duration_compare` <- function(`x`, `y`, `relative` = NULL) {
  .Call(savvy_rs_duration_compare__impl, `x`, `y`, `relative`)
}


`rs_duration_format` <- function(`x`) {
  .Call(savvy_rs_duration_format__impl, `x`)
}


`rs_duration_parse` <- function(`x`) {
  .Call(savvy_rs_duration_parse__impl, `x`)
}


`rs_duration_round` <- function(`x`, `largest`, `smallest`, `increment`, `mode`, `relative` = NULL) {
  .Call(savvy_rs_duration_round__impl, `x`, `largest`, `smallest`, `increment`, `mode`, `relative`)
}


`rs_duration_sort_key` <- function(`x`) {
  .Call(savvy_rs_duration_sort_key__impl, `x`)
}


`rs_duration_total` <- function(`x`, `unit`, `relative` = NULL) {
  .Call(savvy_rs_duration_total__impl, `x`, `unit`, `relative`)
}


`rs_duration_validate` <- function(`x`) {
  .Call(savvy_rs_duration_validate__impl, `x`)
}


`rs_instant_add` <- function(`x`, `duration`) {
  .Call(savvy_rs_instant_add__impl, `x`, `duration`)
}


`rs_instant_diff` <- function(`x`, `y`, `largest`, `smallest`, `increment`, `mode`, `since`) {
  .Call(savvy_rs_instant_diff__impl, `x`, `y`, `largest`, `smallest`, `increment`, `mode`, `since`)
}


`rs_instant_epoch_nanoseconds` <- function(`x`) {
  .Call(savvy_rs_instant_epoch_nanoseconds__impl, `x`)
}


`rs_instant_format` <- function(`x`) {
  .Call(savvy_rs_instant_format__impl, `x`)
}


`rs_instant_from_epoch_nanoseconds` <- function(`x`) {
  .Call(savvy_rs_instant_from_epoch_nanoseconds__impl, `x`)
}


`rs_instant_parse` <- function(`x`) {
  .Call(savvy_rs_instant_parse__impl, `x`)
}


`rs_instant_round` <- function(`x`, `smallest`, `increment`, `mode`) {
  .Call(savvy_rs_instant_round__impl, `x`, `smallest`, `increment`, `mode`)
}


`rs_instant_to_zoned` <- function(`x`, `time_zone`) {
  .Call(savvy_rs_instant_to_zoned__impl, `x`, `time_zone`)
}


`rs_instant_validate` <- function(`x`) {
  .Call(savvy_rs_instant_validate__impl, `x`)
}


`rs_now` <- function() {
  .Call(savvy_rs_now__impl)
}


`rs_plain_date_add` <- function(`year`, `month`, `day`, `duration`, `reject`) {
  .Call(savvy_rs_plain_date_add__impl, `year`, `month`, `day`, `duration`, `reject`)
}


`rs_plain_date_diff` <- function(`x`, `y`, `largest`, `smallest`, `increment`, `mode`, `since`) {
  .Call(savvy_rs_plain_date_diff__impl, `x`, `y`, `largest`, `smallest`, `increment`, `mode`, `since`)
}


`rs_plain_date_field` <- function(`year`, `month`, `day`, `field`) {
  .Call(savvy_rs_plain_date_field__impl, `year`, `month`, `day`, `field`)
}


`rs_plain_date_format` <- function(`year`, `month`, `day`) {
  .Call(savvy_rs_plain_date_format__impl, `year`, `month`, `day`)
}


`rs_plain_date_from_epoch_days` <- function(`days`) {
  .Call(savvy_rs_plain_date_from_epoch_days__impl, `days`)
}


`rs_plain_date_from_parts` <- function(`year`, `month`, `day`, `reject`) {
  .Call(savvy_rs_plain_date_from_parts__impl, `year`, `month`, `day`, `reject`)
}


`rs_plain_date_parse` <- function(`x`) {
  .Call(savvy_rs_plain_date_parse__impl, `x`)
}


`rs_plain_date_time_add` <- function(`x`, `duration`, `reject`) {
  .Call(savvy_rs_plain_date_time_add__impl, `x`, `duration`, `reject`)
}


`rs_plain_date_time_diff` <- function(`x`, `y`, `largest`, `smallest`, `increment`, `mode`, `since`) {
  .Call(savvy_rs_plain_date_time_diff__impl, `x`, `y`, `largest`, `smallest`, `increment`, `mode`, `since`)
}


`rs_plain_date_time_format` <- function(`year`, `month`, `day`, `second_of_day`, `nanos`) {
  .Call(savvy_rs_plain_date_time_format__impl, `year`, `month`, `day`, `second_of_day`, `nanos`)
}


`rs_plain_date_time_parse` <- function(`x`) {
  .Call(savvy_rs_plain_date_time_parse__impl, `x`)
}


`rs_plain_date_time_round` <- function(`x`, `smallest`, `increment`, `mode`) {
  .Call(savvy_rs_plain_date_time_round__impl, `x`, `smallest`, `increment`, `mode`)
}


`rs_plain_date_to_epoch_days` <- function(`year`, `month`, `day`) {
  .Call(savvy_rs_plain_date_to_epoch_days__impl, `year`, `month`, `day`)
}


`rs_plain_time_add` <- function(`second_of_day`, `nanos`, `duration`) {
  .Call(savvy_rs_plain_time_add__impl, `second_of_day`, `nanos`, `duration`)
}


`rs_plain_time_diff` <- function(`x`, `y`, `largest`, `smallest`, `increment`, `mode`, `since`) {
  .Call(savvy_rs_plain_time_diff__impl, `x`, `y`, `largest`, `smallest`, `increment`, `mode`, `since`)
}


`rs_plain_time_format` <- function(`second_of_day`, `nanos`) {
  .Call(savvy_rs_plain_time_format__impl, `second_of_day`, `nanos`)
}


`rs_plain_time_from_parts` <- function(`hour`, `minute`, `second`, `millisecond`, `microsecond`, `nanosecond`, `reject`) {
  .Call(savvy_rs_plain_time_from_parts__impl, `hour`, `minute`, `second`, `millisecond`, `microsecond`, `nanosecond`, `reject`)
}


`rs_plain_time_parse` <- function(`x`) {
  .Call(savvy_rs_plain_time_parse__impl, `x`)
}


`rs_plain_time_round` <- function(`second_of_day`, `nanos`, `smallest`, `increment`, `mode`) {
  .Call(savvy_rs_plain_time_round__impl, `second_of_day`, `nanos`, `smallest`, `increment`, `mode`)
}


`rs_time_zone_canonical` <- function(`x`) {
  .Call(savvy_rs_time_zone_canonical__impl, `x`)
}


`rs_zoned_add` <- function(`x`, `duration`, `reject`) {
  .Call(savvy_rs_zoned_add__impl, `x`, `duration`, `reject`)
}


`rs_zoned_civil` <- function(`x`) {
  .Call(savvy_rs_zoned_civil__impl, `x`)
}


`rs_zoned_diff` <- function(`x`, `y`, `largest`, `smallest`, `increment`, `mode`, `since`) {
  .Call(savvy_rs_zoned_diff__impl, `x`, `y`, `largest`, `smallest`, `increment`, `mode`, `since`)
}


`rs_zoned_format` <- function(`x`) {
  .Call(savvy_rs_zoned_format__impl, `x`)
}


`rs_zoned_from_civil` <- function(`x`, `time_zone`, `disambiguation`, `offset`, `offset_mode`) {
  .Call(savvy_rs_zoned_from_civil__impl, `x`, `time_zone`, `disambiguation`, `offset`, `offset_mode`)
}


`rs_zoned_hours_in_day` <- function(`x`) {
  .Call(savvy_rs_zoned_hours_in_day__impl, `x`)
}


`rs_zoned_offset` <- function(`x`) {
  .Call(savvy_rs_zoned_offset__impl, `x`)
}


`rs_zoned_parse` <- function(`x`, `disambiguation`, `offset_mode`) {
  .Call(savvy_rs_zoned_parse__impl, `x`, `disambiguation`, `offset_mode`)
}


`rs_zoned_round` <- function(`x`, `smallest`, `increment`, `mode`) {
  .Call(savvy_rs_zoned_round__impl, `x`, `smallest`, `increment`, `mode`)
}


`rs_zoned_start_of_day` <- function(`x`) {
  .Call(savvy_rs_zoned_start_of_day__impl, `x`)
}


`rs_zoned_transition` <- function(`x`, `next`) {
  .Call(savvy_rs_zoned_transition__impl, `x`, `next`)
}


